import requests
from bs4 import BeautifulSoup
import argparse
from graphviz import Digraph

transiciones = {
    'q0': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q1': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q4',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q5',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q2': {
        'a': 'q6',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q3': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q7',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q8',
        'ó': 'q0',
        'ú': 'q0'},
    'q4': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q9',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q10',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q5': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q11',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q6': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q12',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q5',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q7': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q13',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q8': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q14',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q9': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q15',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q10': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q16',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q11': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q17',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q12': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q9',
        'f': 'q0',
        'g': 'q0',
        'h': 'q18',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q10',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q13': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q19',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q14': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q20',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q15': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q21',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q16': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q22',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q17': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q23',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q18': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q24',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q19': {
        'a': 'q25',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q26',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q20': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q27',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q21': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q28',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q22': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q23': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q29',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q24': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q30',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q25': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q31',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q5',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q26': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q32',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q27': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q33',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q28': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q29': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q34',
        'ú': 'q0'},
    'q30': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q35',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q31': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q9',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q36',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q10',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q32': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q37',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q33': {
        'a': 'q38',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q34': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q39',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q35': {
        'a': 'q40',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q36': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q41',
        'ú': 'q0'},
    'q37': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q42',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q38': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q43',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q39': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q40': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q41': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q44',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q42': {
        'a': 'q45',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q43': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q18',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q44': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'},
    'q45': {
        'a': 'q1',
        'b': 'q0',
        'c': 'q0',
        'd': 'q0',
        'e': 'q0',
        'f': 'q0',
        'g': 'q0',
        'h': 'q0',
        'i': 'q0',
        'j': 'q0',
        'k': 'q0',
        'l': 'q0',
        'm': 'q2',
        'n': 'q0',
        'ñ': 'q0',
        'o': 'q0',
        'p': 'q0',
        'q': 'q0',
        'r': 'q0',
        's': 'q0',
        't': 'q0',
        'u': 'q0',
        'v': 'q3',
        'w': 'q0',
        'x': 'q0',
        'y': 'q0',
        'z': 'q0',
        'á': 'q0',
        'é': 'q0',
        'í': 'q0',
        'ó': 'q0',
        'ú': 'q0'}}


def extraer_contenido_principal(url):
    try:
        # Solicitar el contenido de la página web
        response = requests.get(url)
        response.raise_for_status()  # Asegurar que no haya errores en la respuesta
        response.encoding = 'utf-8'  # Forzar la codificación a UTF-8
        
        # Crear el objeto BeautifulSoup para analizar el HTML
        soup = BeautifulSoup(response.content, 'html.parser')
        
        # Buscar solo las etiquetas principales: <p>, <h1>, <h2>, <h3>, etc.
        etiquetas_permitidas = soup.find_all(['p', 'h1', 'h2', 'h3'])

        # Verificar si no se encontraron etiquetas permitidas
        if not etiquetas_permitidas:
            return "No se encontraron etiquetas (<p>, <h>) en esta página."
        
        # Extraer el texto respetando los saltos de línea entre elementos
        texto_principal = '\n\n'.join(tag.get_text(strip=True) for tag in etiquetas_permitidas)

        return texto_principal
    except requests.exceptions.RequestException as e:
        return f"Error al acceder a la página: {e}"

def buscador_web(texto_principal):
    estados_finales = {
        'q22' : {
            'palabra' : 'acoso',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q28' : {
            'palabra' : 'acecho',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q38' : {
            'palabra' : 'víctima',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q39' : {
            'palabra' : 'agresión',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q40' : {
            'palabra' : 'machista',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q44' : {
            'palabra' : 'violación',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q45' : {
            'palabra' : 'violencia',
            'cuenta' : 0,
            'posiciones' : []
        }
        
    }  
    texto_procesado = texto_principal.split("\n")
    texto = [ parrafo for parrafo in texto_procesado if parrafo.strip() ] 

    with open("contenido_principal.txt", "w", encoding="utf-8") as archivo:
        archivo.write(texto)

    edo_actual='q0'
    historia = []
    for posY, parrafo in enumerate(texto):
        posX = 1
        for simbolo in parrafo:
            posX += 1
            edo_copia = edo_actual
            edo_actual = transiciones[edo_actual].get(simbolo,'q0')
            if edo_actual in estados_finales:
                estados_finales[edo_actual]['cuenta'] += 1
                tam = len(estados_finales[edo_actual]['palabra'])
                estados_finales[edo_actual]['posiciones'].append((posX-tam,posY))
            historia.append((edo_copia,simbolo,edo_actual))

    return estados_finales, historia

def buscador(archivo_texto):

    estados_finales = {
        'q22' : {
            'palabra' : 'acoso',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q28' : {
            'palabra' : 'acecho',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q38' : {
            'palabra' : 'víctima',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q39' : {
            'palabra' : 'agresión',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q40' : {
            'palabra' : 'machista',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q44' : {
            'palabra' : 'violación',
            'cuenta' : 0,
            'posiciones' : []
        },
        'q45' : {
            'palabra' : 'violencia',
            'cuenta' : 0,
            'posiciones' : []
        }
        
    }
    edo_actual='q0'
    historia = []
    with open(archivo_texto, "r", encoding="utf-8") as archivo:
        posX = 0
        posY = 0
        for linea in archivo:
            posX = 1
            posY += 1
            #linea.strip()
            for simbolo in linea:
                posX += 1
                edo_copia = edo_actual
                edo_actual = transiciones[edo_actual].get(simbolo,'q0')
                if edo_actual in estados_finales:
                    estados_finales[edo_actual]['cuenta'] += 1
                    tam = len(estados_finales[edo_actual]['palabra'])
                    estados_finales[edo_actual]['posiciones'].append((posX-tam,posY))
                historia.append((edo_copia,simbolo,edo_actual))

    return estados_finales, historia


def guardar_resultados(archivo_salida_txt, estados_finales):
    with open(archivo_salida_txt, 'a', encoding='utf-8') as archivo_resultado:
        archivo_resultado.write(f"\n{"-"*80}\n")
        for resultado in estados_finales.values():
            apariciones = f"\n\tPalabra Reservada: {resultado['palabra']} --- # de Apariciones: {resultado['cuenta']}"
            archivo_resultado.write(apariciones + f"\nCoordenadas de '{resultado['palabra']}' encontradas:\n")
            coordenadas = ", ".join(str(coords) for coords in resultado['posiciones'])
            archivo_resultado.write(coordenadas + "\n\n")

def guardar_historia(archivo_historia_txt, historia):
    cadena_historia = ""
    with open(archivo_historia_txt, 'a', encoding='utf-8') as archivo_historia:
        archivo_historia.write(f"\n{"-"*80}\n\n")
        for transicion in historia:
            q_actual, simbolo, q_siguiente = transicion
            cadena_historia += f"\u03B4({q_actual}, {simbolo} = {q_siguiente})\n"
        archivo_historia.write(cadena_historia +"\n\n")


def graficar():
    estados_finales = {'q22', 'q28', 'q38', 'q39', 'q40', 'q44', 'q45'}
    # Crear un objeto Digraph
    afd_grafo = Digraph(format='png')
    for estado, q_transiciones in transiciones.items():
        if estado in estados_finales:
            afd_grafo.node(estado, estado, shape='circle', peripheries='2')
        else:
            afd_grafo.node(estado, estado, shape='circle')
        for simbolo, estado_sig in q_transiciones.items():
            afd_grafo.edge(estado, estado_sig, label=simbolo)

     
    afd_grafo.render('afd_grafo')
#---------------------------------




def modo_manual():
    archivo_txt = 'texto.txt'
    archivo_resultado_txt = 'resultado_busqueda.txt'
    archivo_historia_txt = 'historia.txt'
    opcion = input("\nDesea Ejecutar la Búsqueda en un archivo de Texto de Prueba? (s/n): ")
    while opcion not in ['s','n']:
        opcion = input("Ingresa una opción válida: ")
    if opcion=='s':
        print("\nBuscando Palabras Reservadas en el archivo de Texto mediante un DFA...")
        estados_finales, historia = buscador(archivo_txt)

        guardar_resultados(archivo_resultado_txt, estados_finales)
        print(f"\nResultados de la Búsqueda Guardados correctamente en {archivo_resultado_txt}")

        guardar_historia(archivo_historia_txt, historia)
        print(f"Historia del proceso guardada correctamente en {archivo_historia_txt}")

    opcion = input("\nDesea Ejecutar la Búsqueda en una Página Web? (s/n): ")
    while opcion not in ['s','n']:
        opcion = input("Ingresa una opción válida: ")
    if opcion=='s':
        url = input("Ingresa la URL de la página web para hacer la búsqueda: ")
        print("\nBuscando Palabras Reservadas en la página Web Ingresada mediante un DFA...")
        estados_finales, historia = buscador_web(extraer_contenido_principal(url))
        print("Contenido Principal de la Página Web Guardado en 'contenido_principal.txt'")

        guardar_resultados(archivo_resultado_txt, estados_finales)
        print(f"\nResultados de la Búsqueda Guardados correctamente en {archivo_resultado_txt}")

        guardar_historia(archivo_historia_txt, historia)
        print(f"Historia del proceso guardada correctamente en {archivo_historia_txt}")

def modo_automatico():
    archivo_txt = 'texto.txt'
    archivo_resultado_txt = 'resultado_busqueda.txt'
    archivo_historia_txt = 'historia.txt'

    print("\nBuscando Palabras Reservadas en el archivo de Texto mediante un DFA...")
    estados_finales, historia = buscador(archivo_txt)

    guardar_resultados(archivo_resultado_txt, estados_finales)
    print(f"\nResultados de la Búsqueda Guardados correctamente en {archivo_resultado_txt}")

    guardar_historia(archivo_historia_txt, historia)
    print(f"Historia del proceso guardada correctamente en {archivo_historia_txt}")

    url = "https://efeminista.com/reconocer-a-todas-las-victimas-de-violencias-machistas-un-ejercicio-pendiente/"

    print("\nBuscando Palabras Reservadas en la Página Web de Ejemplo mediante un DFA...")
    estados_finales, historia = buscador_web(extraer_contenido_principal(url))
    print("Contenido Principal de la Página Web Guardado en 'contenido_principal.txt'")

    guardar_resultados(archivo_resultado_txt, estados_finales)
    print(f"\nResultados de la Búsqueda Guardados correctamente en {archivo_resultado_txt}")

    guardar_historia(archivo_historia_txt, historia)
    print(f"Historia del proceso guardada correctamente en {archivo_historia_txt}")

def menu():
    while True:
        print("\n\nBuscador de Palabras Reservadas mediante la implementación de un DFA")
        print("1. Modo Manual")
        print("2. Modo Automático")
        print("3. Salir")

        opcion = input("Seleccione una opción (1, 2 o 3): ")

        # Validación de la entrada usando un while
        while opcion not in ['1', '2', '3']:
            print("Opción inválida. Por favor, ingrese 1, 2 o 3.")
            opcion = input("Seleccione una opción (1, 2 o 3): ")

        # Convertir la opción a entero después de validar
        opcion = int(opcion)

        if opcion == 1:
            graficar()
            print("Grafo del AFD guardado.")
            modo_manual()
        elif opcion == 2:
            graficar()
            print("Grafo del AFD guardado.")
            modo_automatico()
        else:
            print("Saliendo...")
            break

parser = argparse.ArgumentParser(description='Pract 3 TC')
parser.add_argument('-m', '--modo', type=str, default='m', help='Nombre del archivo de salida')
#comando="python p_3_Buscador --modo a"
args = parser.parse_args()

if args.modo == 'a':
    print("\n\nBuscador de Palabras Reservadas mediante la implementación de un DFA")
    modo_automatico()
else:
    menu()